### ISSUE TITLE
Add new overlays repository

### ISSUE THREAD

**Issue by nono6493** [meleu/rpie-art#10]
Not really an issue. After a long work to prepare it, I think my overlay repository for Retropie is ready to be added to your rpie-art.sh script. Here is the URL  : 
https://github.com/nono6493/overlays
You can name it "nono6493 overlay repository" or something like this.

At the time being, only overlays that I have created haves the info.txt file. I will now add an info.txt file to the overlays made by other contributors. 
Sorry if I don't do a pull request. I am still a beginner with github. I have not really understood how to do.
Thank you for your help.

**Comment by meleu** [comment]
done in 70d9f6b137bc40cc8d2534130bb578a017f82e51
