### ISSUE TITLE
[feature request] deal with shader configs

### ISSUE THREAD

**Issue by meleu** [meleu/rpie-art#5]
@UDb23 asked about the possibility to manage shader configs through rpie-art script ([this forum post](https://retropie.org.uk/forum/post/113763)).

I need some investigation about how this stuff works, but I think it's doable.

**Comment by lilbud** [comment]
Well, to set overlays on a per game basis, you have to make the .zip.cfg file like this

> `input_overlay  = ""/opt/retropie/configs/all/retroarch/overlay/RetroPie-Overlays/SNES Mini/Integer Scale/4 by 3/08_space.cfg""


> input_overlay_enable = true


> input_overlay_opacity = 1.000000


> input_overlay_scale = 1.000000


> video_shader = "/opt/retropie/configs/all/retroarch/shaders/crt-pi.glslp"`

Not sure how to do it for everything

**Comment by Wilstorm** [comment]
I'm not quite sure how to do it either. There's several shaders. Unless one is set as the default.

Also another challenge is with DaveJ's crt-pi it has two versions one for horizontal games (crt-pi.glslp) and one for vertical games (crt-pi-vertical.glslp) so you would need to know the orientation of the game. I think dankcushions has that information in a space or comma delimited file with a field that has either H or V for horizontal or vertical.

**Comment by meleu** [comment]
Since there's another tool to make it, I decided to not add such feature on rpie-art.

Thanks guys!

**Comment by Wilstorm** [comment]
Well that's a bummer. No chance in combining the tools? The issue with the other tool is they don't work together at all. The other tool installs the config files in a different folder. When you run a game the other tools configs take priority and change the resolution so the overlays no longer line up.

So basically if you install your tool, run it and install some overlays everything is ok. Now if you run the other tool and copy the generated configs to the specified folder and run a game it doesn't work. The overlays no longer line up. Then other tools configs change the resolution. The game area ends up in the overlay or vice versa. You may use one tool or the other but not both at the same time.

The overlays @UDb23 generates require a static resolution and can't be changed.

The other issue is if you set the global/system shader to horizontal and then install the overlays. You have to manually modify each game.zip.cfg by hand that is vertical. The same if you set the global option to vertical you have to modify each horizontal game by hand.

**Comment by meleu** [comment]
looks like the other tool isn't much "RetroPie-friendly". Maybe asking for it on its own repo worths it. Can you provide a link to it?

I'm a bit busy with other projects currently and can't look at it soon... Sorry.

**Comment by Wilstorm** [comment]
Thanks Meleu. I was just posting the issue so that down the road it might be worth looking into. Right now I manually modify all the game.zip.cfg files to include a shader. Then I manually back them up and restore when I upgrade to a newer version of RetroPie. Your tool is great and works well!
